print('Enter the name of cat 1:')
cat_name_1 = ()
print('Enter the name of cat 2:')
cat_name_2 = ()
print('Enter the name of cat 3:')
cat_name_3 = ()
print('Enter the name of cat 3:')
cat_name_4 = ()
print('the cat names are:')
print(cat_name_1 + ' ' + cat_name_2 + ' ' + cat_name_3 + ' ' + cat_name_4)
